import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../app/providers.dart';
import '../../core/core.dart';
import '../../l10n/strings.dart';

/// The name printed at the top of receipts and statements.
///
/// Set in Settings; until then the business's name from the portal, and
/// until that, the app's own name.
const shopNameKey = 'agentkhata.receipt_shop_name';
const shopPhoneKey = 'agentkhata.receipt_shop_phone';
const shopOwnerKey = 'agentkhata.receipt_shop_owner';
const shopAddressKey = 'agentkhata.receipt_shop_address';
const shopFooterKey = 'agentkhata.receipt_shop_footer';

/// What sits at the top and bottom of every receipt and statement.
class ReceiptHeader {
  const ReceiptHeader({required this.name, this.owner, this.address, this.phone, this.footer});
  final String name;
  final String? owner;
  final String? address;
  final String? phone;
  final String? footer;
}

final receiptHeaderProvider = FutureProvider<ReceiptHeader>((ref) async {
  final p = await SharedPreferences.getInstance();
  String? get(String k) {
    final v = p.getString(k)?.trim();
    return (v == null || v.isEmpty) ? null : v;
  }

  return ReceiptHeader(
    name: get(shopNameKey) ?? get('agentkhata.shop_name_remote') ?? 'এজেন্ট খাতা',
    owner: get(shopOwnerKey),
    address: get(shopAddressKey),
    phone: get(shopPhoneKey),
    footer: get(shopFooterKey),
  );
});

/// The shop block printed at the top of a receipt or statement.
class ShopHeaderBlock extends StatelessWidget {
  const ShopHeaderBlock({super.key, required this.header, required this.code});
  final ReceiptHeader? header;
  final String code;

  @override
  Widget build(BuildContext context) {
    final h = header;
    const faint = TextStyle(color: Colors.black54, fontSize: 11.5);
    return Column(mainAxisSize: MainAxisSize.min, children: [
      Text(h?.name ?? '', textAlign: TextAlign.center, style: const TextStyle(color: Colors.black87, fontSize: 18, fontWeight: FontWeight.w800)),
      if (h?.owner != null) Text(h!.owner!, textAlign: TextAlign.center, style: faint.copyWith(fontWeight: FontWeight.w600, color: Colors.black87)),
      if (h?.address != null) Text(h!.address!, textAlign: TextAlign.center, style: faint),
      if (h?.phone != null) Text('☎ ${bnDigits(h!.phone!, code)}', textAlign: TextAlign.center, style: faint),
    ]);
  }
}

/// A customer's number on a receipt: enough to recognise, not enough to copy.
String maskNumber(String n) {
  final d = n.replaceAll(RegExp(r'\D'), '');
  if (d.length <= 4) return d;
  return '${'•' * (d.length - 3)}${d.substring(d.length - 3)}';
}

/// 01711223344 → 8801711223344, the form wa.me wants.
String? intlBd(String? phone) {
  if (phone == null) return null;
  final d = phone.replaceAll(RegExp(r'\D'), '');
  if (d.isEmpty) return null;
  if (d.startsWith('880')) return d;
  return '880${d.replaceFirst(RegExp(r'^0'), '')}';
}

/// A short receipt number derived from the entry, stable across phones.
String receiptNo(Transaction t) => t.id.replaceAll('-', '').substring(0, 8).toUpperCase();

/// Renders what [key] wraps and hands it to the phone's share sheet, as a PNG
/// or as a PDF around that PNG. WhatsApp, Messenger, imo, Gmail: whatever the
/// agent has installed.
///
/// The PDF carries the rendered image rather than laid-out text so Bangla
/// conjuncts come out exactly as on screen, which a PDF font engine cannot
/// promise.
Future<void> shareRendered(GlobalKey key, {required String name, required String text, required bool pdf}) async {
  final boundary = key.currentContext!.findRenderObject()! as RenderRepaintBoundary;
  final image = await boundary.toImage(pixelRatio: 3);
  final png = (await image.toByteData(format: ui.ImageByteFormat.png))!.buffer.asUint8List();
  if (pdf) {
    final img = pw.MemoryImage(png);
    final doc = pw.Document()
      ..addPage(pw.Page(pageFormat: PdfPageFormat(img.width! / 3, img.height! / 3), margin: pw.EdgeInsets.zero, build: (_) => pw.Image(img)));
    await shareBytes(await doc.save(), '$name.pdf', 'application/pdf', text);
  } else {
    await shareBytes(png, '$name.png', 'image/png', text);
  }
}

/// Writes [bytes] to a real file and shares that. share_plus drops the name
/// of an in-memory file on Android and fails on an empty path, so every
/// share of generated bytes goes through here.
Future<void> shareBytes(List<int> bytes, String fileName, String mime, String text) async {
  final dir = Directory('${(await getTemporaryDirectory()).path}/share');
  await dir.create(recursive: true);
  final safe = fileName.replaceAll(RegExp(r'[^\w.\-\u0980-\u09FF ]'), '_');
  final f = File('${dir.path}/$safe');
  await f.writeAsBytes(bytes, flush: true);
  await SharePlus.instance.share(ShareParams(files: [XFile(f.path, mimeType: mime)], text: text));
}

/// Opens the receipt preview with its share buttons.
Future<void> showReceipt(BuildContext context, WidgetRef ref, Transaction t) {
  return Navigator.of(context).push(MaterialPageRoute(fullscreenDialog: true, builder: (_) => ReceiptScreen(t: t)));
}

class ReceiptScreen extends ConsumerStatefulWidget {
  const ReceiptScreen({super.key, required this.t});
  final Transaction t;

  @override
  ConsumerState<ReceiptScreen> createState() => _ReceiptScreenState();
}

class _ReceiptScreenState extends ConsumerState<ReceiptScreen> {
  final _key = GlobalKey();
  bool _busy = false;

  Future<void> _share({required bool pdf}) async {
    if (_busy) return;
    setState(() => _busy = true);
    try {
      await shareRendered(_key, name: 'receipt-${receiptNo(widget.t)}', text: _summary(), pdf: pdf);
    } finally {
      if (mounted) setState(() => _busy = false);
    }
  }

  String _summary() {
    final code = ref.read(localeProvider);
    final t = widget.t;
    final s = ref.s;
    final type = code == 'bn' ? t.type.labelBn : t.type.label;
    final amt = Fmt.moneyOf(code, t.amount.value.abs());
    return '${s('receipt')} #${receiptNo(t)} — $type $amt${t.trxId != null ? ' • TrxID ${t.trxId}' : ''}';
  }

  Future<void> _whatsapp() async {
    final t = widget.t;
    final customer = t.customerId == null ? null : (ref.read(customersProvider).value ?? []).where((c) => c.id == t.customerId).firstOrNull;
    final to = intlBd(customer?.phone ?? t.counterparty);
    final uri = Uri.parse('https://wa.me/${to ?? ''}?text=${Uri.encodeComponent(_summary())}');
    await launchUrl(uri, mode: LaunchMode.externalApplication);
  }

  @override
  Widget build(BuildContext context) {
    final s = ref.s;
    return Scaffold(
      appBar: AppBar(title: Text(s('receipt'))),
      body: ListView(padding: const EdgeInsets.all(20), children: [
        Center(child: RepaintBoundary(key: _key, child: ReceiptCard(t: widget.t))),
        const SizedBox(height: 24),
        FilledButton.icon(
          onPressed: _busy ? null : () => _share(pdf: true),
          icon: const Icon(Icons.picture_as_pdf_outlined),
          label: Text(s('share_pdf')),
          style: FilledButton.styleFrom(minimumSize: const Size.fromHeight(52)),
        ),
        const SizedBox(height: 10),
        Row(children: [
          Expanded(
            child: OutlinedButton.icon(
              onPressed: _busy ? null : () => _share(pdf: false),
              icon: const Icon(Icons.image_outlined),
              label: Text(s('share_image')),
              style: OutlinedButton.styleFrom(minimumSize: const Size.fromHeight(48)),
            ),
          ),
          const SizedBox(width: 10),
          Expanded(
            child: OutlinedButton.icon(
              onPressed: _whatsapp,
              icon: const Icon(Icons.chat, color: Color(0xFF25D366)),
              label: const Text('WhatsApp'),
              style: OutlinedButton.styleFrom(minimumSize: const Size.fromHeight(48)),
            ),
          ),
        ]),
        const SizedBox(height: 8),
        Text(s('share_hint'), textAlign: TextAlign.center, style: Theme.of(context).textTheme.bodySmall),
      ]),
    );
  }
}

/// The receipt itself: white paper, black ink, whatever the app theme, so a
/// screenshot or a print looks like a receipt.
class ReceiptCard extends ConsumerWidget {
  const ReceiptCard({super.key, required this.t});
  final Transaction t;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final s = ref.s;
    final code = ref.watch(localeProvider);
    final header = ref.watch(receiptHeaderProvider).value;
    final wallets = ref.watch(walletsProvider).value ?? [];
    final wallet = wallets.where((w) => w.id == t.walletId).firstOrNull;
    final customers = ref.watch(customersProvider).value ?? [];
    final customer = t.customerId == null ? null : customers.where((c) => c.id == t.customerId).firstOrNull;
    String money(int v) => Fmt.moneyOf(code, v);
    const ink = Colors.black87;
    const faint = Colors.black54;
    Widget row(String k, String v, {bool strong = false}) => Padding(
          padding: const EdgeInsets.symmetric(vertical: 3),
          child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text(k, style: const TextStyle(color: faint, fontSize: 13)),
            const SizedBox(width: 12),
            Expanded(child: Text(v, textAlign: TextAlign.end, style: TextStyle(color: ink, fontSize: strong ? 18 : 13, fontWeight: strong ? FontWeight.w800 : FontWeight.w600))),
          ]),
        );
    Widget rule() => Padding(
          padding: const EdgeInsets.symmetric(vertical: 10),
          child: Row(children: List.generate(40, (i) => Expanded(child: Container(height: 1, color: i.isEven ? Colors.black26 : Colors.transparent)))),
        );

    return Container(
      width: 320,
      padding: const EdgeInsets.fromLTRB(20, 22, 20, 18),
      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(6), boxShadow: const [BoxShadow(color: Colors.black26, blurRadius: 12, offset: Offset(0, 4))]),
      child: DefaultTextStyle(
        style: const TextStyle(color: ink),
        child: Column(mainAxisSize: MainAxisSize.min, children: [
          ShopHeaderBlock(header: header, code: code),
          const SizedBox(height: 4),
          // Letter-spacing tears Bangla conjuncts apart, so only English gets it.
          Text(s('receipt').toUpperCase(), style: TextStyle(color: faint, fontSize: 11, letterSpacing: code == 'bn' ? 0 : 2)),
          rule(),
          row(s('receipt_no'), receiptNo(t)),
          row(s('time'), bnDigits(DateFormat('d MMM yyyy, h:mm a', code == 'bn' ? 'bn' : 'en').format(t.occurredAt), code)),
          row(s('type'), code == 'bn' ? t.type.labelBn : t.type.label),
          if (wallet != null) row(s('account'), wallet.nameIn(code)),
          if (t.counterparty != null) row(s('phone'), bnDigits(maskNumber(t.counterparty!), code)),
          if (customer != null) row(s('customer'), customer.name),
          if (t.trxId != null) row('TrxID', t.trxId!),
          rule(),
          row(s('amount'), money(t.amount.value.abs()), strong: true),
          if (t.fee.value != 0) row(s('fees'), money(t.fee.value)),
          if (t.note != null && t.note!.isNotEmpty) row(s('note'), t.note!),
          rule(),
          Text(header?.footer ?? s('receipt_thanks'), textAlign: TextAlign.center, style: const TextStyle(color: faint, fontSize: 12)),
        ]),
      ),
    );
  }
}
